site_name: oxd Docs
site_description: Documenation for oxd OpenID Connect and UMA client software
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources 
repo_url: https://github.com/GluuFederation/docs-oxd
theme: readthedocs 
theme_dir: ./theme/mkdocs/ 
pages: 
 
- [index.md, Home]

# oxd Server
- [oxdserver/index.md, oxd Server, Protocol]
- [install/index.md, oxd Server, Installation]
- [conf/index.md, oxd Server, Configuration]
- [oxdserver/logs/index.md, oxd Server, Logs]

# Libraries

- [libraries/python/index.md, Libraries, Python]
- [libraries/java/index.md, Libraries, Java]
- [libraries/php/index.md, Libraries, PHP]
- [libraries/node/index.md, Libraries, Node]
- [libraries/ruby/index.md, Libraries, Ruby]
- [libraries/csharp/index.md, Libraries, CSharp]

# Plugins
- [plugin/wordpress/index.md, Plugin, Wordpress]
- [plugin/magento/index.md, Plugin, Magento]
- [plugin/drupal/index.md, Plugin, Drupal]
- [plugin/opencart/index.md, Plugin, OpenCart]
- [plugin/sugarcrm/index.md, Plugin, SugarCRM]
- [plugin/suitecrm/index.md, Plugin, SuiteCRM]
- [plugin/roundcube/index.md, Plugin, RoundCube]

# Framework
- [framework/spring/index.md, Framework, Java Spring]
- [framework/play/index.md, Framework, Java Play Framework]
- [framework/ruby/index.md, Framework, Ruby on Rails]
- [framework/python/index.md, Framework, Python Flask]
- [framework/node/index.md, Framework, Node/Express]

