site_name: oxD Docs
site_description: Documenation for oxD
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources 
repo_url: https://github.com/GluuFederation/docs-oxd
theme: readthedocs 
theme_dir: ./theme/mkdocs/ 
pages: 
 
- [index.md, Home]

# oxD Server
- [oxdserver/index.md, oxD Server, Protocol]
- [oxdserver/install/index.md, oxD Server, Installation]
- [oxdserver/conf/index.md, oxD Server, Configuration]
- [oxdserver/logs/index.md, oxD Server, Logs]
- [oxdserver/other/index.md,oxD Server, Other Information]


# Libraries

- [libraries/python/index.md, Libraries, Python]
- [libraries/java/index.md, Libraries, Java]
- [libraries/php/index.md, Libraries, PHP]
- [libraries/node/index.md, Libraries, Node]
- [libraries/ruby/index.md, Libraries, Ruby]

# Plugins
- [plugin/wordpress/index.md, Plugin, Wordpress]
- [plugin/magento/index.md, Plugin, Magento]
- [plugin/drupal/index.md, Plugin, Drupal]
- [plugin/opencart/index.md, Plugin, OpenCart]
- [plugin/sugarcrm/index.md, Plugin, SugarCRM]
- [plugin/suitecrm/index.md, Plugin, SuiteCRM]
- [plugin/roundcube/index.md, Plugin, RoundCube]
