site_name: oxd Docs
site_description: Documenation for oxd OpenID Connect and UMA client software
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources 
# repo_url: https://github.com/GluuFederation/docs-oxd
repo_url: https://github.com/GluuFederation/docs-oxd/
theme: readthedocs 
theme_dir: ./theme/mkdocs/ 

markdown_extensions:
- admonition

pages: 
 
- [index.md, Home]

# Protocol
- [protocol/index.md, oxd Server, Protocol]

# 2.4.4
- [2.4.4/install/index.md, oxd Server, Installation]
- [2.4.4/conf/index.md, oxd Server, Configuration]
- [2.4.4/logs/index.md, oxd Server, Logs]
## Libraries
- [2.4.4/libraries/api-client-libraries.md, Libraries, oxd API Client Libraries]
- [2.4.4/libraries/python/index.md, Libraries, Python]
- [2.4.4/libraries/java/index.md, Libraries, Java]
- [2.4.4/libraries/php/index.md, Libraries, PHP]
- [2.4.4/libraries/node/index.md, Libraries, Node]
- [2.4.4/libraries/ruby/index.md, Libraries, Ruby]
- [2.4.4/libraries/csharp/index.md, Libraries, CSharp]
- [2.4.4/libraries/perl/index.md, Libraries, Perl]

## Plugins
- [2.4.4/plugin/wordpress/index.md, Plugin, Wordpress]
- [2.4.4/plugin/magento/index.md, Plugin, Magento]
- [2.4.4/plugin/drupal/index.md, Plugin, Drupal]
- [2.4.4/plugin/opencart/index.md, Plugin, OpenCart]
- [2.4.4/plugin/sugarcrm/index.md, Plugin, SugarCRM]
- [2.4.4/plugin/suitecrm/index.md, Plugin, SuiteCRM]
- [2.4.4/plugin/roundcube/index.md, Plugin, RoundCube]

## Framework
- [2.4.4/framework/spring/index.md, Framework, Java Spring]
- [2.4.4/framework/play/index.md, Framework, Java Play Framework]
- [2.4.4/framework/ruby/index.md, Framework, Ruby on Rails]
- [2.4.4/framework/python/index.md, Framework, Python Flask]
- [2.4.4/framework/node/index.md, Framework, Node/Express]

# master docs
- [install/index.md, hidden, hidden]
- [conf/index.md, hidden, hidden]
- [logs/index.md, hidden, hidden]
- [libraries/api-client-libraries.md, hidden, hidden]
- [libraries/python/index.md, hidden, hidden]
- [libraries/java/index.md, hidden, hidden]
- [libraries/php/index.md, hidden, hidden]
- [libraries/node/index.md, hidden, hidden]
- [libraries/ruby/index.md, hidden, hidden]
- [libraries/csharp/index.md, hidden, hidden]
- [libraries/perl/index.md, hidden, hidden]
- [plugin/wordpress/index.md, hidden, hidden]
- [plugin/magento/index.md, hidden, hidden]
- [plugin/drupal/index.md, hidden, hidden]
- [plugin/opencart/index.md, hidden, hidden]
- [plugin/sugarcrm/index.md, hidden, hidden]
- [plugin/suitecrm/index.md, hidden, hidden]
- [plugin/roundcube/index.md, hidden, hidden]
- [framework/spring/index.md, hidden, hidden]
- [framework/play/index.md, hidden, hidden]
- [framework/ruby/index.md, hidden, hidden]
- [framework/python/index.md, hidden, hidden]
- [framework/node/index.md, hidden, hidden]


