site_name: oxD Docs
site_description: Documenation for oxD
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources 
repo_url: https://github.com/GluuFederation/docs-oxd
theme: readthedocs 
theme_dir: ./theme/mkdocs/ 
pages: 
 
- [index.md, Home]

# oxD Server
- [oxdserver/index.md, oxD Server, Introduction]
- [oxdserver/install/index.md, oxD Server, Installation]
- [oxdserver/run/index.md, oxD Server, Run]
- [oxdserver/troubleshooting/index.md, oxD Server, Troubleshooting]

# Plugins
- [plugin/index.md, Plugins, Introduction]
- [plugin/python/index.md, Plugins, Python]
- [plugin/php/index.md, Plugins, Php]
- [plugin/php/library/index.md, Php library]
- [plugin/php/cms/index.md, CMS]
- [plugin/php/cms/wordpress/index.md, CMS, Wordpress plugin]
- [plugin/php/cms/magento/index.md, CMS, Magento extension]
- [plugin/php/cms/drupal/index.md, CMS, Drupal module]
- [plugin/php/crm/index.md, CRM]
- [plugin/php/crm/sugarcrm/index.md, CRM, SugarCRM module]
- [plugin/php/crm/suitecrm/index.md, CRM, SuiteCRM module]
